#!/usr/bin/env python3
"""
The automation layer.

A workflow rule's Function action can only pick a function whose category is
`automation`, and an automation function cannot be called from another function.
The reverse is also true: `standalone` is the only category other functions can
call. So the two categories do different jobs, and the adapter between them is
deliberately thin — every line of real logic lives in the standalone library,
which is the part worth testing and reusing.

Each adapter below is the entry point for exactly one workflow rule. The
argument names are what the rule's argument mapping binds to record fields.
"""
import json

ADAPTERS = [
    # The trigger guard lives HERE, in version-controlled code, rather than in the
    # workflow rule's criteria builder. The rule fires on the record action; the
    # adapter decides whether the condition is actually met. That keeps the whole
    # trigger contract reviewable in a diff instead of buried in a settings UI,
    # and it is the part most likely to need changing later.
    ("wfConfirmAdmission", "Leads", "Edit",
     [("leadId", "int")],
     'lead = zoho.crm.getRecordById("Leads", leadId);\n'
     'if(ifnull(lead.get("Lead_Status"), "") == "Admission Confirmed")\n{\n'
     '    standalone.confirmAdmission(leadId);\n}'),

    ("wfEnforceSingleCurrentYear", "Academic_Years", "Create or Edit",
     [("yearId", "string")],
     'yr = zoho.crm.getRecordById("Academic_Years", yearId.toLong());\n'
     'if(ifnull(yr.get("Is_Current"), false))\n{\n'
     '    standalone.enforceSingleCurrentYear(yearId);\n}'),

    ("wfAttendanceCreated", "Attendance", "Create",
     [("attendanceId", "string")],
     'standalone.attendanceRollupFromRecord(attendanceId, "create");'),

    ("wfAttendanceEdited", "Attendance", "Edit",
     [("attendanceId", "string")],
     'standalone.attendanceRollupFromRecord(attendanceId, "edit");'),

    ("wfValidateMark", "Marks", "Create or Edit",
     [("markId", "int")], 'standalone.validateMark(markId);'),

    ("wfPublishExamResults", "Examinations", "Edit",
     [("examId", "int")],
     'ex = zoho.crm.getRecordById("Examinations", examId);\n'
     'if(ifnull(ex.get("Results_Published"), false))\n{\n'
     '    standalone.publishExamResults(examId);\n}'),

    ("wfPaymentCreated", "Payments", "Create",
     [("paymentId", "int")],
     'standalone.allocatePayment(paymentId);\nstandalone.generateReceipt(paymentId);'),

    ("wfPaymentEdited", "Payments", "Edit",
     [("paymentId", "int")], 'standalone.allocatePayment(paymentId);'),

    ("wfInvalidatePortalCache", "Students", "Create or Edit",
     [("studentId", "int")], 'standalone.invalidatePortalCache(studentId);'),

    ("wfProcessLeaveApproval", "Leave_Requests", "Edit",
     [("leaveId", "int")],
     'lv = zoho.crm.getRecordById("Leave_Requests", leaveId);\n'
     'st = ifnull(lv.get("Status"), "").toString();\n'
     'if(st == "Approved" || st == "Rejected")\n{\n'
     '    standalone.processLeaveApproval(leaveId);\n}'),
]

out, doc = [], []
for name, module, trigger, params, body in ADAPTERS:
    out.append({
        "name": name, "file": "automation", "ret": "void", "category": "automation",
        "params": [{"name": p, "type": t} for p, t in params],
        "workflow": "// %s : %s\n%s\n" % (module, trigger, body),
        "module": module, "trigger": trigger,
    })
    doc.append("| %s | %s | %s | `%s(%s)` |" %
               (module, trigger, name, name, ", ".join(p for p, _ in params)))

json.dump(out, open('tools/automation.json', 'w'), indent=1)

with open('deluge/automation/README.md', 'w') as f:
    f.write("""# The automation layer

A workflow rule's **Function** action can only pick a function whose category is
`automation`. An `automation` function cannot be called from another function, and
`standalone` is the only category that can be. The two categories therefore do
different jobs, and the adapter between them is kept deliberately thin: every line of
real logic lives in the standalone library under `../crm`, which is the part worth
testing and reusing. These eleven functions exist only to be the entry point of
exactly one workflow rule each.

Generated by `tools/make_automation.py`; deployed with the same POST-then-PUT flow as
the standalone library.

| Module | Trigger | Adapter | Call |
|---|---|---|---|
""")
    for name, module, trigger, params, body in ADAPTERS:
        f.write("| %s | %s | `%s` | `%s` |\n" %
                (module, trigger, name, body.split("\n")[-1].strip()))

print("%d adapters" % len(out))
