#!/usr/bin/env python3
"""
The automation layer.

A workflow rule's Function action can only pick a function whose category is
`automation`, and an automation function cannot be called from another function.
The reverse is also true: `standalone` is the only category other functions can
call. So the two categories do different jobs, and the adapter between them is
deliberately thin — every line of real logic lives in the standalone library,
which is the part worth testing and reusing.

Each adapter below is the entry point for exactly one workflow rule. The
argument names are what the rule's argument mapping binds to record fields.
"""
import json

ADAPTERS = [
    ("wfConfirmAdmission", "Leads", "Edit, Lead_Status = Admission Confirmed",
     [("leadId", "int")], 'standalone.confirmAdmission(leadId);'),

    ("wfEnforceSingleCurrentYear", "Academic_Years", "Create or Edit, Is_Current = true",
     [("yearId", "string")], 'standalone.enforceSingleCurrentYear(yearId);'),

    ("wfAttendanceCreated", "Attendance", "Create",
     [("enrollmentId", "string"), ("status", "string")],
     'standalone.updateAttendanceRollup(enrollmentId, "", status, "create");'),

    ("wfAttendanceEdited", "Attendance", "Edit, Status changed",
     [("enrollmentId", "string")],
     '// the old status is not available to a workflow, so recount authoritatively\n'
     'standalone.recomputeEnrollmentAttendance(enrollmentId);'),

    ("wfAttendanceDeleted", "Attendance", "Delete",
     [("enrollmentId", "string")],
     'standalone.recomputeEnrollmentAttendance(enrollmentId);'),

    ("wfValidateMark", "Marks", "Create or Edit",
     [("markId", "int")], 'standalone.validateMark(markId);'),

    ("wfPublishExamResults", "Examinations", "Edit, Results_Published = true",
     [("examId", "int")], 'standalone.publishExamResults(examId);'),

    ("wfPaymentCreated", "Payments", "Create",
     [("paymentId", "int")],
     'standalone.allocatePayment(paymentId);\nstandalone.generateReceipt(paymentId);'),

    ("wfPaymentEdited", "Payments", "Edit, Status changed",
     [("paymentId", "int")], 'standalone.allocatePayment(paymentId);'),

    ("wfInvalidatePortalCache", "Students", "Create or Edit (Parent, Status, Current_Class_Section)",
     [("studentId", "int")], 'standalone.invalidatePortalCache(studentId);'),

    ("wfProcessLeaveApproval", "Leave_Requests", "Edit, Status is Approved or Rejected",
     [("leaveId", "int")], 'standalone.processLeaveApproval(leaveId);'),
]

out, doc = [], []
for name, module, trigger, params, body in ADAPTERS:
    out.append({
        "name": name, "file": "automation", "ret": "void", "category": "automation",
        "params": [{"name": p, "type": t} for p, t in params],
        "workflow": "// %s : %s\n%s\n" % (module, trigger, body),
        "module": module, "trigger": trigger,
    })
    doc.append("| %s | %s | %s | `%s(%s)` |" %
               (module, trigger, name, name, ", ".join(p for p, _ in params)))

json.dump(out, open('tools/automation.json', 'w'), indent=1)

with open('deluge/automation/README.md', 'w') as f:
    f.write("""# The automation layer

A workflow rule's **Function** action can only pick a function whose category is
`automation`. An `automation` function cannot be called from another function, and
`standalone` is the only category that can be. The two categories therefore do
different jobs, and the adapter between them is kept deliberately thin: every line of
real logic lives in the standalone library under `../crm`, which is the part worth
testing and reusing. These eleven functions exist only to be the entry point of
exactly one workflow rule each.

Generated by `tools/make_automation.py`; deployed with the same POST-then-PUT flow as
the standalone library.

| Module | Trigger | Adapter | Call |
|---|---|---|---|
""")
    for name, module, trigger, params, body in ADAPTERS:
        f.write("| %s | %s | `%s` | `%s` |\n" %
                (module, trigger, name, body.split("\n")[-1].strip()))

print("%d adapters" % len(out))
